server:
  port: 9901

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userms_db
    username: root
    password: root  
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

      driver-class-name: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL57Dialect
    