server:
  port: 9901

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userms_db
    username: root
    password: root  
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true   
    