server:
  port: 9902
  
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelms_db
    username: postgres
    password: root  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   
        
eureka:
  instance:
    prefer-ip-address: true
  client   :
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:9904/eureka             