server:
  port: 9902
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelms_db
    username: postgres
    password: root  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   